language: cpp

os: linux
sudo: required
dist: trusty

compiler:
  - gcc

addons:
  apt:
    packages:
      - doxygen
      - graphviz

git:
  depth: 3
  submodules: false

before_install:
  - git submodule update --init --recursive

install:
  - make -C solvers

script:
  - cmake -DUSE_CRYPTOMINISAT=ON -DUSE_LINGELING=ON -DUSE_MINISAT=ON -DUSE_PICOSAT=ON . && make && ctest --verbose
  - util/check-doxygen-errors.sh
