name: check-include-guards

on: [push, pull_request]

jobs:
  include-guards:
    name: Check include guards
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check include guard of commonsat.h
      uses: sbeyer/include-guards-check-action@v1.0.0
      with:
        pattern: '{file}'
        only: '^commonsat/commonsat\.h'
    - name: Check include guards of remaining files
      uses: sbeyer/include-guards-check-action@v1.0.0
      with:
        ignore: '^\(commonsat/commonsat\.h\|test/\)'
